#!/bin/bash

ln -sfrT config/nvim ~/.config/nvim 
ln -sfrT config/.tmux.conf ~/.config/tmux/tmux.conf
ln -sfrT config/alacritty ~/.config/alacritty
ln -sfrT config/hypr ~/.config/hypr
ln -sfrT config/waybar ~/.config/waybar
ln -sfrT config/mako ~/.config/mako
ln -sfrT config/niri ~/.config/niri
