#!/bin/bash

ln -s ~/tools/dotfiles/nvim ~/.config/nvim 
ln -s ~/tools/dotfiles/.tmux.conf ~/.config/tmux/tmux.conf
ln -s ~/tools/dotfiles/wshine.zsh-theme ~/.oh-my-zsh/themes/wshine.zsh-theme
ln -s ~/tools/dotfiles/alacritty ~/.config/alacritty
