#! /bin/sh

# auto start-up
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x xscreensaver > /dev/null || xscreensaver -no-splash &
pgrep -x picom > /dev/null || picom -b &
xset s 300 600 +dpms
xss-lock -l -- xscreensaver-command -lock
feh --bg-center "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/1920x1200.svg"
~/.config/polybar/launch.sh


# wm configuration
bspc monitor -d I II III IV V VI
bspc config border_width         3
bspc config window_gap           8
bspc config focused_border_color '#8f3d3d'
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
