#! /bin/sh

# auto start-up
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x xscreensaver > /dev/null || xscreensaver -no-splash &
pgrep -x picom > /dev/null || picom -b &
xset +dpms 300 600
xss-lock -l -- xscreensaver-command -lock
feh --bg-fill /usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg
rofi -modi drun


# wm configuration
~/.config/bspwm/monitor-setup
~/.config/polybar/launch.sh
bspc config border_width         3
bspc config window_gap           8
bspc config focused_border_color '#512475'
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
